### ISSUE TITLE
failed test during installation 

### ISSUE THREAD

**Issue by imyiningliu** [grahamgower/genomatnn#43]
Hi! I was following the installing instructions and got 6 errors. I'm wondering whether I could get some help with this? The errors are "AttributeError: 'str' object has no attribute 'decode'" and "FileNotFoundError: [Errno 2] No such file or directory: 'bgzip'" (I tried to fix the bgzip error by uninstalling and reinstalling the bgzip package, but still got the same error when running the tests again.) I've attached the full error message below. 

Thank you in advance for your help!

```
======================================================================
ERROR: test suite for <class 'tests.test_cli.TestApply'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/yiningliu/genomatnn/tests/test_cli.py", line 52, in setUpClass
    cli.main(f"train --seed 1 {cls.config_file}".split())
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 608, in main
    args.func(args.conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 120, in do_train
    do_eval(conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 171, in do_eval
    model = models.load_model(conf.nn_hdf5_file)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

======================================================================
ERROR: test suite for <class 'tests.test_cli.TestApply_phased'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/yiningliu/genomatnn/tests/test_cli.py", line 52, in setUpClass
    cli.main(f"train --seed 1 {cls.config_file}".split())
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 608, in main
    args.func(args.conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 120, in do_train
    do_eval(conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 171, in do_eval
    model = models.load_model(conf.nn_hdf5_file)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

======================================================================
ERROR: test suite for <class 'tests.test_cli.TestEval'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/yiningliu/genomatnn/tests/test_cli.py", line 52, in setUpClass
    cli.main(f"train --seed 1 {cls.config_file}".split())
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 608, in main
    args.func(args.conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 120, in do_train
    do_eval(conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 171, in do_eval
    model = models.load_model(conf.nn_hdf5_file)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

======================================================================
ERROR: test suite for <class 'tests.test_cli.TestEval_phased'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/yiningliu/genomatnn/tests/test_cli.py", line 52, in setUpClass
    cli.main(f"train --seed 1 {cls.config_file}".split())
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 608, in main
    args.func(args.conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 120, in do_train
    do_eval(conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 171, in do_eval
    model = models.load_model(conf.nn_hdf5_file)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

======================================================================
ERROR: test suite for <class 'tests.test_cli.TestVcfplot'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/yiningliu/genomatnn/tests/test_cli.py", line 52, in setUpClass
    cli.main(f"train --seed 1 {cls.config_file}".split())
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 608, in main
    args.func(args.conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 120, in do_train
    do_eval(conf)
  File "/Users/yiningliu/genomatnn/genomatnn/cli.py", line 171, in do_eval
    model = models.load_model(conf.nn_hdf5_file)
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/site-packages/tensorflow-2.4.1-py3.8-macosx-10.9-x86_64.egg/tensorflow/python/keras/saving/hdf5_format.py", line 182, in load_model_from_hdf5
    model_config = json_utils.decode(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

======================================================================
ERROR: test_compare_ts_vcf_genotype_matrixes (tests.test_convert.TestGenotypeMatrixes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yiningliu/genomatnn/tests/test_convert.py", line 167, in test_compare_ts_vcf_genotype_matrixes
    subprocess.run(["bgzip", vcf_file])
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/yiningliu/opt/anaconda3/envs/genomatnn/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bgzip'

----------------------------------------------------------------------
Ran 25 tests in 1053.544s

FAILED (errors=6)
```

**Comment by grahamgower** [comment]
Hi @imyiningliu! I see you're running MacOSX. I've only tested on Linux, so there may be unanticipated problems on a Mac. But maybe if those two errors get fixed, things will work anyhow.

* `AttributeError: 'str' object has no attribute 'decode'`. Tensorflow seems to be incompatible with some versions of the `h5py` package (https://github.com/tensorflow/tensorflow/issues/44467). I'm not sure why the incorrect version is installed in your environment, but in my environment I have h5py version `2.10.0`. As far as I can tell, tensorflow automatically installed this older version for me. Can you trying installing the older version manually? E.g. `pip install h5py==2.10.0`.
* `FileNotFoundError: [Errno 2] No such file or directory: 'bgzip'`. It looks like the `bgzip` binary is not in your PATH. If you type `bgzip` at the command line, I guess you get an error ("command not found" or similar)? You'll need to figure out where `bgzip` is living on your system and make sure that folder is in your `PATH` environment variable.

I've also just updated the installation instructions, because I had (different) problems installing everything today. If you get the following error from the tests, try the updated instructions.
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

Let me know if that helps. And thanks for trying out genomatnn!

**Comment by grahamgower** [comment]
Hi @imyiningliu. I've updated the installation instructions, and provided a conda `environment.yml` file. This should simplify installation. The continuous integration tests are also now running successfully on MacOS (albeit slowly). So I'm going to close this issue. If you have further problems, please open a new issue. Thanks!
